-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color5 = '#E7C664'
local Color10 = '#222f44'
local Color2 = '#9ED072'
local Color12 = '#3b242d'
local Color3 = '#76CCE0'
local Color11 = '#132e37'
local Color7 = '#181a1f'
local Color16 = '#dcdcdc'
local Color15 = '#7f8490'
local Color6 = '#E2E2E3'
local Color8 = '#9da5b4'
local Color9 = '#abb2bf'
local Color14 = '#495162'
local Color0 = '#7F8490'
local Color1 = '#B39DF3'
local Color13 = '#353c4b'
local Color4 = '#FC5D7C'

highlight('Comment', nil, Color0, nil)
highlight('Constant', nil, Color1, nil)
highlight('Number', nil, Color1, nil)
highlight('Function', nil, Color2, nil)
highlight('Function', nil, Color2, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color2, nil)
highlight('Error', nil, nil, 'italic')
highlight('Keyword', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color4, nil)
highlight('Type', nil, Color4, nil)
highlight('String', nil, Color5, nil)
highlight('Identifier', nil, Color6, nil)
highlight('Comment', nil, nil, 'italic')
highlight('Keyword', nil, nil, 'italic')
highlight('StatusLine', Color8, Color7, nil)
highlight('WildMenu', Color7, Color9, nil)
highlight('Pmenu', Color7, Color9, nil)
highlight('PmenuSel', Color9, Color10, nil)
highlight('PmenuThumb', Color7, Color9, nil)
highlight('DiffAdd', Color11, nil, nil)
highlight('DiffDelete', Color12, nil, nil)
highlight('Normal', Color7, Color9, nil)
highlight('Visual', Color13, nil, nil)
highlight('CursorLine', Color13, nil, nil)
highlight('ColorColumn', Color13, nil, nil)
highlight('SignColumn', Color7, nil, nil)
highlight('LineNr', nil, Color14, nil)
highlight('TabLine', Color7, Color15, nil)
highlight('TabLineSel', Color16, Color10, nil)
highlight('TabLineFill', Color7, Color15, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('TSLabel', 'Type')
link('TSProperty', 'TSField')
link('NonText', 'Comment')
link('TSString', 'String')
link('TSTagDelimiter', 'Type')
link('TSNamespace', 'TSType')
link('TSOperator', 'Operator')
link('TSField', 'Constant')
link('TSFunction', 'Function')
link('TSParameter', 'Constant')
link('TSPunctBracket', 'MyTag')
link('TelescopeNormal', 'Normal')
link('TSRepeat', 'Repeat')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSFloat', 'Number')
link('TSType', 'Type')
link('Whitespace', 'Comment')
link('Conditional', 'Operator')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Macro', 'Function')
link('TSParameterReference', 'TSParameter')
link('TSNumber', 'Number')
link('Folded', 'Comment')
link('TSFuncMacro', 'Macro')
link('TSComment', 'Comment')
link('TSKeyword', 'Keyword')
link('Operator', 'Keyword')
link('Repeat', 'Conditional')
link('CursorLineNr', 'Identifier')
link('TSConstant', 'Constant')
link('TSTag', 'MyTag')
link('TSConditional', 'Conditional')
