#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

yabai -m config external_bar               all:0:0     \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.2          \
                active_window_opacity      0.88         \
                normal_window_opacity      0.83         \
                window_animation_duration  0.3          \
                insert_feedback_color      0xff9dd274 \
                split_ratio                0.50         \
                auto_balance               off          \
                auto_padding               on           \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                2            \
                bottom_padding             2            \
                left_padding               2            \
                right_padding              2            \
                window_gap                 5
# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Linear|Beekeeper Studio|Bruno|LuLu|미리보기|iPhone 미러링|Calculator|Software Update|Dictionary|System Preferences|Archive Utility|App Store|Postman|Slack|Activity Monitor|Sip|CleanShot X|시스템 설정|FaceTime|메모|활성 상태 보기|사진|Raycast|Finder|서체 관리자|Sleeve|음악|IINA|Transmission|음성 메모|카카오톡|메시지)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Arc" app="^Arc$" title="^(hyezo|General|Max|Shortcuts|Links|Advanced)$" manage=off
yabai -m rule --add label="Raycast" app="^Raycast$" title="^(General)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded.."
