return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  dependencies = "OXY2DEV/markview.nvim",
  opts = {
    ensure_installed = {
      "lua",
      "tsx",
      "typescript",
      "javascript",
      "swift",
      "css",
      "scss",
      "html",
      "jsonc",
      "jsdoc",
      "markdown",
      "markdown_inline",
      "dockerfile",
      "graphql",
      "toml",
      "yaml",
      "xml",
      "vim",
      "fish",
      "swift",
      "rust",
      "gitignore",
      "prisma",
      "regex",
      -- "glsl",
    },
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
  },
}
